// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCix0Rmg-qskBKgDw_iO4wOhus7iSZ55F8',
    appId: '1:969301263840:web:151bc412763d66f31f9785',
    messagingSenderId: '969301263840',
    projectId: 'wechat-d19d0',
    authDomain: 'wechat-d19d0.firebaseapp.com',
    storageBucket: 'wechat-d19d0.appspot.com',
    measurementId: 'G-C7V577KN06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzYalyHrFBa2mrZLdZ6KNU3I61fOY7zcg',
    appId: '1:969301263840:android:808b10c7e54d6e4c1f9785',
    messagingSenderId: '969301263840',
    projectId: 'wechat-d19d0',
    storageBucket: 'wechat-d19d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwv5JJhlf6aQ2ROGoHzv16usJP57NnIFw',
    appId: '1:969301263840:ios:98d8a483cee453611f9785',
    messagingSenderId: '969301263840',
    projectId: 'wechat-d19d0',
    storageBucket: 'wechat-d19d0.appspot.com',
    iosBundleId: 'com.example.fitivationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwv5JJhlf6aQ2ROGoHzv16usJP57NnIFw',
    appId: '1:969301263840:ios:9f29f7616f740c451f9785',
    messagingSenderId: '969301263840',
    projectId: 'wechat-d19d0',
    storageBucket: 'wechat-d19d0.appspot.com',
    iosBundleId: 'com.example.fitivationApp.RunnerTests',
  );
}
